# new config

ENV: &default_env
  SECRET_TOKEN: $
  TEST_KEY: "oui"

timeout: 200

pipeline:
  jobs:
    build:
      steps:
        - cmd: cargo build

    test_rust:
      needs: [build]
      env:
        RUST_LOG: debug
      steps:
        - cmd: cargo test --test cli_test
          contaner: rust:1.89

    echo_test:
      needs: [build]
      steps:
        - cmd: echo test 1
          container: ubuntu:latest

    sleep_test:
      steps:
        - cmd: sleep 5
        
    deploy:
      needs: [test_rust, echo_test]
      steps:
        - cmd: echo je suis arriver a la fin
          blocking: true